[package]
name = "Tverdohlib/mrrw"
description = "Useful tool that were accidentaly created at Squad Devlopers"
version = "0.1.0"
license = "MIT"
authors = ["Squad Developers"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dev-dependencies]
